### ISSUE TITLE
FileNotFoundError `requirements.txt`

### ISSUE THREAD

**Issue by oniboni** [aka-raccoon/hatch-aws#9]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

hatch-aws 1.0.0

### Steps to reproduce

* update project setup to conform `1.0.0` (`include` -> `tool.hatch.build.force-include`)

Additional version info: 
SAM CLI, version 1.73.0
pyenv 2.3.12

### Expected behavior

Should create `target` directory before writing into `target / "requirements.txt"`.

### Actual behavior

```sh
$ hatch build -t aws
[aws]
Building lambda functions ...
<package> ... <class 'pathlib.PosixPath'> /<path>/.aws-sam/build/<package>/<lambda>/requirements.txt
Traceback (most recent call last):
  File "/<path>/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/<path>/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/<hatchenvpath>/lib/python3.9/site-packages/hatchling/__main__.py", line 6, in <module>
    sys.exit(hatchling())
  File "/<hatchenvpath>/lib/python3.9/site-packages/hatchling/cli/__init__.py", line 26, in hatchling
    command(**kwargs)
  File "/<hatchenvpath>/lib/python3.9/site-packages/hatchling/cli/build/__init__.py", line 75, in build_impl
    for artifact in builder.build(
  File "/<hatchenvpath>/lib/python3.9/site-packages/hatchling/builders/plugin/interface.py", line 158, in build
    artifact = version_api[version](directory, **build_data)
  File "/<hatchenvpath>/lib/python3.9/site-packages/hatch_aws/builder.py", line 105, in build_standard
    self.build_lambda(aws_lambda=aws_lambda, shared_files=shared_files)
  File "/<hatchenvpath>/lib/python3.9/site-packages/hatch_aws/builder.py", line 61, in build_lambda
    requirements_file.write_text(data="\n".join(deps), encoding="utf-8")
  File "/<path>/.pyenv/versions/3.9.16/lib/python3.9/pathlib.py", line 1285, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/<path>/.pyenv/versions/3.9.16/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/<path>/.pyenv/versions/3.9.16/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/<path>/.aws-sam/build/<package>/<lambda>/requirements.txt'
```

### Affected runtime and version

python@3.9.16

### Affected package manager and version

pip@23.0.1

### Affected OS and version

openSUSE Tumbleweed 20230221

**Comment by trash-panda-v91-beta** [comment]
Thanks @oniboni for the fix. It's released in [1.1.0](https://github.com/aka-raccoon/hatch-aws/releases/tag/1.1.0).
